apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-inkspire-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       app: my-app-inkspire
  template:
    metadata:
      labels:
        app: my-app-inkspire
    spec:
      containers:
      - name: my-app-inkspire-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
